msg_dragon_kill: "The dream is over. Your mind clears, the portal opens..." # DragonKillText
msg_max_health_restore: "Your max health has been restored." # MaxHealthRestoreText
msg_perma_death: " has perished, never to return." # PermaDeathServerText
perma_ban_reason: "The last thing you feel is the never-ending darkness as your soul is consumed..." # PermaBanText
msg_totem_clutch: "A magical force emanates from the totem, sparing you from certain death." # TotemDeathPlayerText
msg_health_steal: "Harnessing the power of dark magic, you feed your soul at the expense of another's." # HealthStealText
msg_health_loss: "You may have escaped with your life, but the damage has already been done..." # HealthLossText
msg_ban_spared: "You are given a new lease on life..." # n/a
msg_ban_on_death: "The last thing you feel is the never-ending darkness as your soul is consumed..." # BanOnDeathText
msg_revive_status: "Reviving"
msg_death_standard: "%PLAYER% confronted their mortality"
msg_no_perms: "You don't have permission to use this command."
setmax_player_not_found: "Cannot find the player specified."
setmax_health_not_valid: "The value specified is not a valid number."
setmax_out_of_bounds: "The value specified is out of bounds."
setmax_success: "Max health updated successfully."
enable_success: "Hardcore++ has been enabled."
disable_success: "Hardcore++ has been disabled."
enable_fail: "Hardcore++ is already enabled."
disable_fail: "Hardcore++ is already disabled."
msg_arg_length_error: "%d arguments provided for '%s'; expected %d."

dragon_kill_restores_max_health: true # DragonKillRestoresMaxHealthEnabled
bleeding_effect: true # BloodEffectEnabled
allow_totems: true # TotemOfUndyingWorks
max_health_loss_on_death: 2.0 # LoseMaxHealthOnRespawnAmmount
death_announce: true # AnnounceDeathEnabled
custom_death_msg: false # CustomDeathMessagesEnabled
lose_max_health_on_death: true # LoseMaxHealthOnRespawnEnabled
respawn_effects: true # RespawnSoundEnabled
ban_on_death: false # BanOnDeathEnabled
ban_duration: 12 # BanOnDeathHoursAmmount
perma_ban_on_final_death: true # PermaBanOnFinalDeathEnabled


