name: HardcorePlusPlus
version: 1.0.0
main: me.arrivals.hardcoreplusplus.HardcorePlus
api-version: 1.19
authors: [ arrivals, griimnak ]
description: Fork of griimnak's HardcorePlus
website: https://andremoire.com
commands:
  hardcoreplusplus:
    description: Administrative commands for HardcorePlusPlus.
    usage: /<command>
    aliases: [ hcpp ]
permissions:
  hardcoreplus.admin:
    description: Admin commands like setting max hp for players, etc.
  hardcoreplus.ban_exempt:
    description: Grants a player ban exemption when death on ban is enabled.