name: HardcorePlusPlus
version: '${version}'
main: com.courtega.hardcoreplusplus.HardcorePlusPlus
api-version: '1.21'
authors: [ courtega, griimnak ]
description: Fork of griimnak's HardcorePlus
website: https://courtega.com
commands:
  hcpp:
    description: Administrative commands for HardcorePlusPlus.
    usage: /<command>
    # aliases: [ hcpp ]
  permissions:
    hardcoreplusplus.admin:
      description: Admin commands like setting max hp for players, etc.
    hardcoreplusplus.ban_exempt:
      description: Grants a player ban exemption when death on ban is enabled.